#!/bin/bash
#
# show AUR updates

AUR=$(pacaur -k | wc -l)

if [ "$AUR" -gt 0 ]
   then
       echo "<span foreground='#87AFAF'> </span>$AUR"
   else 
       exit 0
   fi

case $BLOCK_BUTTON in
    # left click, check arch linux homepage 
    1) $BROWSER https://www.archlinux.org ;; 
esac
