#!/bin/bash
# AUR updates
#------------------------------------------------------------------------

AUR=$(pacaur -k | wc -l)

#------------------------------------------------------------------------

if [ "$AUR" -gt 0 ]
   then
       echo "<span foreground='#87AFAF'> </span>$AUR"
   else 
       exit 0
   fi

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) chromium --app=http://ald.mindbrain.io ;; # left click, read arch linux news feeds 
esac
