#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INSTANCE="${1:-BAT0}"
ALERT_LOW="${2:-16}" # color will turn red under this value (default: 10%)
UPOWER="/usr/bin/upower"

if [ ! -x "$UPOWER" ]; then
	echo "upower not found"
	exit 1
fi

$UPOWER -i /org/freedesktop/UPower/devices/battery_$INSTANCE |
	awk -v alert_low=$ALERT_LOW '
/state:/ {
	state = $2
}
/time to full:/ {
	remaining_time = $4 " " substr ($5, 0, 1)
}
/time to empty:/ {
	remaining_time = $4 " " substr ($5, 0, 1)
}
/percentage:/ {
	percentage = $2;
}
END {
	if (state == "charging")
        label = ""
	else if (percentage == "100%")
		label = ""
	else if (percentage > 99)
		label = ""
	else if (percentage > 75)
		label = ""
	else if (percentage > 50)
		label = ""
	else if (percentage > 25)
		label = ""
    else if (percentage > 10) 
		label = ""
    else if (percentage > 5)  
		label = ""
	
    # full text & "$@" > /dev/null;
    print label " " percentage

	# short text
	print label " " percentage

	# color
	gsub(/%$/,"",percentage)
    if (percentage == "100")
		print "#c5c8c6"
    else if (state == "charging")
		print "#c5c8c6"
    else if (+ percentage < + alert_low)
        print "#cc6666"
    else if (percentage < 26)
        print "#af9f87"
    else
        print "#7ea3a3"
}
'
# mouse buttons
case $BLOCK_BUTTON in
  3) toggle-dpms ;; # left click, control DPMS 
  2) toggle-red ;;  # right click, redshift on/off
  1) getacpi ;; # dialog with battery info
  5) sudo brightness up ;; 
  # xbacklight doesn't work with modesetting use brightness script
  4) sudo brightness down ;; 
esac
