#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# modified by leofa

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${100:-20}" # color will turn red above this value (default: 80%)

usage=$(df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
	print $5
	use=$5
	# no need to continue parsing
	exit 0
}

END {
	gsub(/%$/,"",use)
	if (100 - use < alert_low) {
		# color
		print "#CC6666"
	}}')

echo "<span foreground='#87AFAF' > </span>$usage"

case $BLOCK_BUTTON in
 1) i3-msg exec rofi-find ;; #left click, locate +xdg-open files with rofi
 2) i3-msg exec caja ;; #right click, open filemanager 
 3) i3-msg exec 'caja --browser' #middle click, open filemanager
esac
