#!/bin/bash
# Script to get unread google mail.
#------------------------------------------------------------------------

# User and password secured
. ~/.private/accounts

#------------------------------------------------------------------------

COUNT=`curl -su $MAIL_USER:$MAIL_PASS https://mail.google.com/mail/feed/atom || echo "<fullcount>0</fullcount>"`
COUNT=`echo "$COUNT" | grep -oPm1 "(?<=<fullcount>)[^<]+" `

#------------------------------------------------------------------------

if [ "$COUNT" -gt 0 ] 
   then
       echo " <span foreground='#b294bb'></span> $COUNT "
  else
       exit 0
   fi

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) termite --name mutt --title mutt -e mutt ;;
  3) $BROWSER https://mail.google.com
esac
