#!/bin/env bash

used=`free -h | sed -n '2p' | awk -F' ' '{print $3}'`
total=`free -h | sed -n '2p' | awk -F' ' '{print $2}'`

echo "<span foreground='#b294bb' >  </span>$used "
#echo "$used/$total"

case $BLOCK_BUTTON in
    1) termite -e "sh -c 'journalctl -f | ccze -A'" --title journalctl --name log --hold;;
esac
