#!/bin/env bash

used=`free -h | sed -n '2p' | awk -F' ' '{print $3}'`
total=`free -h | sed -n '2p' | awk -F' ' '{print $2}'`

echo "<span font='8' font_weight='ultralight' foreground='#B294BB' > </span>$used"
#echo "$used/$total"

case $BLOCK_BUTTON in
    1) termite --exec "sh -c 'journalctl -f | ccze -A' --name 'log_term'" ;;
esac
