#!/bin/bash
# Pacman updates
#------------------------------------------------------------------------

PACMAN=$(checkupdates | wc -l)

#------------------------------------------------------------------------

if [ "$PACMAN" -gt 10 ]
   then
       echo "<span foreground='#81A2BE'> </span>$PACMAN"
   #     
   else 
       exit 0
   fi

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) chromium --app=http://ald.mindbrain.io ;; # left click, read arch linux news feeds 
esac
