#!/bin/bash
# Pacman updates
#------------------------------------------------------------------------

PACMAN=$(checkupdates | wc -l)

#------------------------------------------------------------------------

if [ "$PACMAN" -gt 0 ]
   then
       echo "<span foreground='#81A2BE'> </span><span foreground='#B4B7B4'>$PACMAN</span>"
   #     
   else 
       exit 0
   fi

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) chromium --app=http://ald.mindbrain.io ;; # left click, read arch linux news feeds 
  3) termite --exec "pacaur -Syu" --name "pacaur" --hold ;; # right click, update system
esac
