#!/bin/bash

PING=$(ping -c 1 $BLOCK_INSTANCE | grep -m 1 -o "[0-9]*[\.]*[0-9]* ms"| cut -d " " -f1) 

if [[ $PING ]]; then
      echo "<span font='8' foreground='#B294BB' weight='ultraheavy' >@</span><span font='1' foreground='#282a2e'>/</span>$PING<span font='2' foreground='#282a2e'>/</span><span foreground='#969896'>ms</span>"
  else
      echo "<span foreground='#B294BB' weight='ultraheavy' >NO</span><span font='2' foreground='#282a2e'>/</span>ping" 
  fi
