#!/bin/bash

ping=$(ping -c 1 $BLOCK_INSTANCE | grep -m 1 -o "[0-9]*[\.]*[0-9]* ms"| cut -d " " -f 1) 

echo "<span foreground='#586E75' >[</span><span font='10' foreground='#81a2be' > </span><span font='2' foreground='#282a2e'>/</span>$ping<span font='2' foreground='#282a2e'>/</span><span weight='heavy' foreground='#B294BB'>ms</span><span foreground='#586E75' >]</span>"
