#!/bin/sh
WIN=$(xdotool getactivewindow) 
if [ -n "$WIN" ]; 
   then 
       #echo "<span font_weight='bold' foreground='#586E75'>〉</span>"
       echo "<span font_weight='normal' foreground='#586E75'> ⵏ</span>"
   else 
       exit 0
   fi
