#!/bin/bash
# wifi signal quality

# if no interface is found, use the first device with a global scope
INTERFACE="${BLOCK_INSTANCE:-wlan0}"
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")
# get external ip from duch website
WANIP=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
SSID=$(iwgetid $INTERFACE -r)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# if the machine has no battery or wireless connection, the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

# wifi signal bars
  if [[ $QUALITY -ge 80 ]]; then
      echo "<span  font='11' foreground='#abb59f' underline='single' underline_color='#586e75'>****</span>"
  elif [[ $QUALITY -lt 80 ]]; then
      echo "<span  font='11' foreground='#abb59f' underline='single' underline_color='#586e75'>***</span>" 
  elif [[ $QUALITY -lt 60 ]]; then
      echo "<span  font='11' foreground='#abb59f' underline='single' underline_color='#586e75'>**</span>" #orange   
  elif [[ $QUALITY -lt 40 ]]; then
      echo "<span  font='11' foreground='#abb59f' underline='single' underline_color='#586e75'>*</span>" #red
fi

# mouse buttons  
case $BLOCK_BUTTON in
    3) rofi-connm ;; # rofi connection manager
    1) netinfo ;; # yad gtk network info dialog
esac

