#!/bin/bash

#------------------------------------------------------------------------

# if no interface is found, use the first device with a global scope
INTERFACE="${BLOCK_INSTANCE:-wlan0}"
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")
# get external ip from duch website
WANIP=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
SSID=$(iwgetid $INTERFACE -r)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

# if the machine has no battery or wireless connection, the corresponding block should not show.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit 0

echo "<span foreground='#87aab5' >$SSID</span>"

#-----------------------------------------------------------------------

# mouse buttons  

case $BLOCK_BUTTON in
    1) netinfo ;; # netwerkinfo
    2) termite --title "wifi-menu" --name "wifi-menu" -e "sudo wifi-menu -o" ;; # connect with wifi-menu
    3) sh -c "netctl list | cut -b 3- | rofi -dmenu -p 'netctl:' -width 22 -yoffset '-300' -xoffset '365' | ifne xargs sudo -A netctl switch-to" #switch netctl profile (depends on ifine from moreutils)
esac

