#!/bin/sh
win=$(xdotool getactivewindow) 
if [ -n "$win" ]; 
   then echo "@"
   else exit 0
   fi

case $BLOCK_BUTTON in
  1) i3-msg floating toggle ;;
  2) i3-msg layout tabbed ;;
  3) i3-msg layout toggle split ;;
  4) i3-msg workspace next ;;
  5) i3-msg workspace prev ;;	  
esac
