#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INSTANCE="${1:-BAT0}"
ALERT_LOW="${2:-11}" # color will turn red under this value (default: 10%)
UPOWER="/usr/bin/upower"

if [ ! -x "$UPOWER" ]; then
	echo "upower not found"
	exit 1
fi

$UPOWER -i /org/freedesktop/UPower/devices/battery_$INSTANCE |
	awk -v alert_low=$ALERT_LOW '
/state:/ {
	state = $2
}
/time to full:/ {
	remaining_time = $4 " " substr ($5, 0, 1)
}
/time to empty:/ {
	remaining_time = $4 " " substr ($5, 0, 1)
}
/percentage:/ {
	percentage = $2;
}
END {
	if (state == "charging")
		label = ""
	else if (percentage == "100%")
		label = ""
	else if (percentage > 75)
		label = ""
	else if (percentage > 50)
		label = ""
	else if (percentage > 25)
		label = ""
    else if (percentage > 10) 
		label = ""
    else  
		label = ""
	
    # full text & "$@" > /dev/null;
	print label " " percentage

	# short text
	print label " " percentage

	# color
	gsub(/%$/,"",percentage)
	if (+ percentage < + alert_low)
		print "#ed6b6b"
}
'
#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) dpmstoggle & "$@" > /dev/null ;; # left click, control DPMS 
  2) togglered & "$@" > /dev/null ;;  # right click, redshift on/off
#  1) yad --no-buttons --text-info --geometry=500x260+$X+20 --class "yad_bat" --margins=10 --filename=<(acpi -V) ;;
  1) yad_logout & "$@" > /dev/null ;; # logout dialog
  5) xbacklight -inc 10 ;; # scroll up, increase brightness
  4) xbacklight -dec 10 ;; # scroll down, decrease brightness
esac
