#!/bin/sh
WIN=$(xdotool getactivewindow) 
if [ -n "$WIN" ]; 
   then echo "X"
   else exit 0 
   fi

case $BLOCK_BUTTON in
  3) sh -c xkill > /dev/null;;
  1) xdotool getactivewindow windowraise windowunmap ;;
esac
