#!/bin/sh
WIN=$(xdotool getactivewindow) 

if [ -n "$WIN" ]; 
   then 
      echo "<span font='10' weight='light' foreground='#A3685A'>🞩</span>"
   else 
       exit 0
   fi

case $BLOCK_BUTTON in
  3) sh -c xkill "$@" &>/dev/null ;;
  1) i3-msg kill ;;
  4) i3-msg focus right ;;
  5) i3-msg focus left ;;	 
esac
