#!/bin/sh
WIN=$(xdotool getactivewindow) 
if [ -n "$WIN" ]; 
   then echo  "<span  font='9' weight='light' foreground='#8A8A8A'> 🞩</span>"
   else exit 0 
   fi

case $BLOCK_BUTTON in
  3) sh -c xkill > /dev/null;;
  1) xdotool getactivewindow windowraise windowunmap ;;
esac
