#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# modified by leofa to show used disk percentage

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${100:-20}" # color will turn red above this value (default: 80%)

df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
	# full text
	print $5 

	# short text
	print $5 

	use=$5 

	# no need to continue parsing
	exit 0
}

END {
	gsub(/%$/,"",use)
	if (100 - use < alert_low) {
		# color
		print "#CC6666"
	}
}

'
case $BLOCK_BUTTON in
  1) caja  & "$@" > /dev/null ;;
  2) yad_df & "$@" > /dev/null ;;
  3) mate-search-tool  & "$@" > /dev/null ;;
esac
