#!/bin/sh
WIN=$(xdotool getactivewindow) 
if [ -n "$WIN" ]; 
   then
       echo -n '<span foreground="#6D8891">[ </span>'; xtitle | cut -c 1-30 
   else 
       exit 0
   fi

case $BLOCK_BUTTON in
  1) i3-msg floating toggle ;;
  2) i3-msg layout tabbed ;;
  3) i3-msg layout toggle split ;;
  4) i3-msg workspace next ;;
  5) i3-msg workspace prev ;;	  
esac
