#!/bin/sh

#load averages
load1="$(cut -d ' ' -f1 /proc/loadavg)"
load2="$(cut -d ' ' -f2 /proc/loadavg)"
load3="$(cut -d ' ' -f3 /proc/loadavg)"

# short text
echo "<span foreground='#B4B7B4'> </span><span foreground='#C5C8C6'>$load1</span><span foreground='#b294bb'>₁</span>"

# long text
#echo "<span foreground='#B4B7B4'> </span><span foreground='#E0E0E0'>$load1₁ </span><span foreground='#C5C8C6'>$load2₅ </span><span foreground='#B4B7B4'>$load3₁₀</span>"

case $BLOCK_BUTTON in
  3) termite --exec htop --name 'htop_term' --hold "$@" &>/dev/null ;;
  1) termite --exec glances --name 'glances_term' --hold "$@" &>/dev/null ;;
esac
