#!/bin/env bash

used=`free -h | sed -n '2p' | awk -F' ' '{print $3}'`
total=`free -h | sed -n '2p' | awk -F' ' '{print $2}'`

echo "$used"
#echo "$used/$total"

case $BLOCK_BUTTON in
  1) termite --exec "sh -c 'journalctl -f | ccze -A'" --name 'log_term' ;;
  3) termite --exec "sh -c 'journalctl -b -0 | ccze -A; journalctl -f | ccze -A'" --name 'log_term' ;;
esac
