#!/bin/sh
WIN=$(xdotool getactivewindow) 
if [ -n "$WIN" ]; 
   then 
       echo "<span font='8' weight='normal' foreground='#969896'>🗖</span>"
    else 
       exit 0
    fi

case $BLOCK_BUTTON in
  1) i3-msg floating toggle ;;
  3) i3-msg layout toggle split ;;
  4) i3-msg focus right ;;
  5) i3-msg focus left ;;	 
esac
