#!/bin/bash

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# if the machine has no battery or wireless connection, the corresponding block should display error.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && echo "<span foreground='#586E75'>[</span><span foreground='#B4B7B4'></span><span foreground='#B4B7B4'> X</span><span foreground='#586E75'>]</span>"

SSID=$(iwgetid $INTERFACE -r)

echo "<span foreground='#586E75'>[</span><span foreground='#87AFAF'> </span><span foreground='#B4B7B4'>$SSID</span><span foreground='#586E75'>]</span>"

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
   1) xdotool key Super_L+slash ;; # chrome launcher shortcut
   3) xdotool key Super_L+Shift+XF86Reload ;; #wifi connect
   2) echo -n "$IPADDR" | xclip -q -se c | notify-send 'IP-adres' 'naar klembord gekopieerd' ;; #copy ip to clipboard
esac

#------------------------------------------------------------------------

echo "$IPADDR" # full text
echo "$IPADDR" # short text
