#!/bin/bash

#------------------------------------------------------------------------

# if no interface is found, use the first device with a global scope
INTERFACE="${BLOCK_INSTANCE:-wlan0}"
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")
# get external ip from duch website
WANIP=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
SSID=$(iwgetid $INTERFACE -r)
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

# if the machine has no battery or wireless connection, the corresponding block should display error.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && echo "<span foreground='#B4B7B4'></span><span foreground='#A3685A'> X</span>"

#------------------------------------------------------------------------

  if [[ $QUALITY -ge 80 ]]; then
      echo "<span foreground='#B4B7B4'></span><span foreground='#87AFAF'> $SSID</span>"
  elif [[ $QUALITY -lt 80 ]]; then
      echo "<span foreground='#B4B7B4'></span><span foreground='#87AFAF'> $SSID</span>" 
  elif [[ $QUALITY -lt 60 ]]; then
      echo "<span foreground='#B4B7B4'></span><span foreground='#87AFAF'> $SSID</span>" #orange   
  elif [[ $QUALITY -lt 40 ]]; then
      echo "<span foreground='#B4B7B4'></span><span foreground='#87AFAF'> $SSID</span>" #red
fi

#-----------------------------------------------------------------------

# mouse buttons  

case $BLOCK_BUTTON in
    1) xdotool key Super_L+XF86Reload ;; # switch profiles with netmenu (shortcuts defined in i3cnf)
   2) xdotool key Super_L+Shift+XF86Reload ;; # connect with wifi-menu
esac

