#!/usr/bin/env bash
set -e

# source https://wiki.archlinux.org/index.php/Chrome_OS_devices#Post_installation_configuration

dir=`pwd`
if [ ! -e "${dir}/${0}" ]; then
  echo "Script not called from within repository directory. Aborting."
  exit 2
fi
dir="${dir}/.."

echo "Installing chromebook drivers..."
pacaur --needed --noedit --noconfirm -S \
  xf86-input-cmt-git \

echo "Add user to input group..."
sudo usermod -a -G input $USER

echo "Add my touchpad tweaks..."
echo 'Section "InputClass"
    Identifier      "touchpad peppy cyapa"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    MatchProduct    "cyapa"
    #added tweaks by leofa: 
    #more responsive, sensitive pointer + osx style scrolling
    Option          "Merge Max Ratio" "0.53"
    Option          "Split Merge Max Movement" "6.1"
    Option          "Tap Minimum Pressure" "1.0"
    Option          "Two Finger Pressure Diff Thresh" "10" 
    Option          "Two Finger Pressure Diff Factor" "0.9"
    Option          "Australian Scrolling" "1"
    Option          "Pointer Sensitivity" "5"
	Option          "Scroll Sensitivity" "4"    
	Option          "T5R2 Three Finger Click Enable" "1"
	Option          "Stationary Wiggle Filter Enabled" "1"
EndSection' > /tmp/peppy.conf
sudo cp /tmp/peppy.conf /etc/X11/xorg.conf.d/60-touchpad-my-cmt-peppy.conf
rm /tmp/peppy.conf    
 
echo "Set X11 keymap us chromebook"
sudo localectl set-x11-keymap us chromebook altgr-intl eurosign:5
ln -sfn ${dir}/.Xmodmap ${HOME}/.Xmodmap

echo "Fixing  suspend issues..."
# touchpad wakeup
echo "w /proc/acpi/wakeup - - - - TPAD" > /tmp/disable-touchpad-wakeup.conf
sudo cp /tmp/disable-touchpad-wakeup.conf /etc/tmpfiles.d/disable-touchpad-wakeup.conf
rm /tmp/disable-touchpad-wakeup.conf

# suspend fix systemd service
echo "#!/bin/bash

awk '{if ($1 != "LID0" && $3 == "*enabled") print $1}' < /proc/acpi/wakeup | 
while read NAME
do echo "$NAME" > /proc/acpi/wakeup
done

exit 0" > /tmp/suspend-device-fix.sh
sudo cp /tmp/suspend-device-fix.sh /usr/local/sbin/suspend-device-fix.sh
sudo chmod +x /usr/local/sbin/suspend-device-fix.sh
rm /tmp/suspend-device-fix.sh

echo "[Unit]
Description=Suspend Fix

[Service]
Type=simple
ExecStart=/usr/local/sbin/suspend-device-fix.sh

[Install]
WantedBy=multi-user.target" > /tmp/suspend-fix.service
sudo cp /tmp/suspend-fix.service /etc/systemd/system/suspend-fix.service
rm /tmp/suspend-fix.service
sudo systemctl start suspend-fix.service
sudo systemctl enable suspend-fix.service

sudo mkdir -p /etc/rc.d
echo "echo 1 > /sys/devices/pci0000\:00/0000\:00\:1d.0/remove" > /tmp/rc.local 
sudo cp /tmp/rc.local /etc/rc.d/rc.local
rm /tmp/rc.local

echo "#!/bin/bash

case $1/$2 in
  pre/*)
    # Unbind ath9k for preventing error and full sleep mode (wakeup by LID after 
hibernating) 
    echo -n "0000:01:00.0" | tee /sys/bus/pci/drivers/ath9k/unbind
    # Unbind snd_hda_intel for sound
    echo -n "0000:00:1b.0" | tee /sys/bus/pci/drivers/snd_hda_intel/unbind
    echo -n "0000:00:03.0" | tee /sys/bus/pci/drivers/snd_hda_intel/unbind
    ;;
  post/*)
    # Bind ath9k for preventing error and and full sleep mode (wakeup by LID 
after hibernating) 
    echo -n "0000:01:00.0" | tee /sys/bus/pci/drivers/ath9k/bind
    # bind snd_hda_intel for sound
    echo -n "0000:00:1b.0" | tee /sys/bus/pci/drivers/snd_hda_intel/bind
    echo -n "0000:00:03.0" | tee /sys/bus/pci/drivers/snd_hda_intel/bind
    ;;
esac" > /tmp/cros-sound-suspend.sh
sudo cp /tmp/cros-sound-suspend.sh /usr/lib/systemd/system-sleep/cros-sound-suspend.sh
rm /tmp/cros-sound-suspend.sh

echo "Fixing sound issues..."

echo "options snd_hda_intel index=1 model=alc283-sense-combo" > /tmp/alsa.conf
sudo cp /tmp/alsa.conf /etc/modprobe.d/alsa.conf
rm /tmp/alsa.conf

cp ${dir}/.asoundrc ${HOME}/.asoundrc

echo "Improve wifi signal quality..."
    echo "options ath9k btcoex_enable=1 bt_ant_diversity=1 ps_enable=0" > /tmp/ath9k.conf 
    sudo cp /tmp/ath9k.conf /etc/modprobe.d/ath9k.conf
    rm /tmp/ath9k.conf
